#!/bin/sh
# Usage: stripPicture fullname mime exportPicture

fullname="$1"
mime="$2"
exportPicture="$3"
LOG=~/.log

echo $mime >> $LOG

# thumbnail options by mime type
case "$mime" in

      application/x-krita)
      unzip -p "$fullname" preview.png > "$exportPicture"
      exit
      ;;
      
      image/openraster)
      unzip -p "$fullname" Thumbnails/thumbnail.png > "$exportPicture"
      exit
      ;;

      image/x-gimp-palette)
      echo convert_palette.py -o "$exportPicture" -f image "$fullname" >> $LOG 2>&1
      convert_palette.py -o "$exportPicture" -f image "$fullname"
      exit
      ;;

      application/x-adobe-swatch-exchange)
      echo convert_palette.py -o "$exportPicture" -f image "$fullname" >> $LOG 2>&1
      convert_palette.py -o "$exportPicture" -f image "$fullname"
      exit
      ;;

      video/*)
      ffmpegthumbnailer -i "$fullname" -o "$exportPicture" -c png >> $LOG 2>&1
      exit
      ;;

      application/x-blender)
      blender-thumbnailer.py "$fullname" "$exportPicture" >> $LOG 2>&1
      exit
      ;;

      *)
#     case trap
      exit
      
esac
